# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sharp/pa26/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sharp/pa26/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/sharp/pa26/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/sharp/pa26/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/sharp/pa26/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/sharp/pa26/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/sharp/pa26/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/sharp/pa26/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/sharp/pa26/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/sharp/pa26/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/sharp/pa26/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt

PRODUCT_COPY_FILES += \
    vendor/sharp/pa26/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/sharp/pa26/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/sharp/pa26/proprietary/bin/diag_mdlog:system/bin/diag_mdlog \
    vendor/sharp/pa26/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/sharp/pa26/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/sharp/pa26/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/sharp/pa26/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/sharp/pa26/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/sharp/pa26/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/sharp/pa26/proprietary/bin/radish:system/bin/radish \
    vendor/sharp/pa26/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/sharp/pa26/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/sharp/pa26/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/sharp/pa26/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/sharp/pa26/proprietary/etc/data/dsi_config.xml:system/etc/data/dsi_config.xml \
    vendor/sharp/pa26/proprietary/etc/data/netmgr_config.xml:system/etc/data/netmgr_config.xml \
    vendor/sharp/pa26/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/sharp/pa26/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/sharp/pa26/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/sharp/pa26/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/sharp/pa26/proprietary/etc/sensor_def_qcomdev.conf:system/etc/sensor_def_qcomdev.conf \
    vendor/sharp/pa26/proprietary/framework/ConnectivityExt.jar:system/framework/ConnectivityExt.jar \
    vendor/sharp/pa26/proprietary/framework/qcnvitems.jar:system/framework/qcnvitems.jar \
    vendor/sharp/pa26/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/sharp/pa26/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/sharp/pa26/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/sharp/pa26/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/sharp/pa26/proprietary/lib/libmdmdetect.so:system/lib/libmdmdetect.so \
    vendor/sharp/pa26/proprietary/lib/libwcnss_qmi.so:system/lib/libwcnss_qmi.so \
    vendor/sharp/pa26/proprietary/vendor/bin/mm-pp-daemon:system/vendor/bin/mm-pp-daemon \
    vendor/sharp/pa26/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    vendor/sharp/pa26/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/sharp/pa26/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/sharp/pa26/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/sharp/pa26/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/sharp/pa26/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/sharp/pa26/proprietary/vendor/lib/hw/activity_recognition.msm8974.so:system/vendor/lib/hw/activity_recognition.msm8974.so \
    vendor/sharp/pa26/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/sharp/pa26/proprietary/vendor/lib/hw/sensors.msm8974.so:system/vendor/lib/hw/sensors.msm8974.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libdataitems.so:system/vendor/lib/libdataitems.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/sharp/pa26/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/sharp/pa26/proprietary/vendor/lib/liblqe.so:system/vendor/lib/liblqe.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/sharp/pa26/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/sharp/pa26/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/sharp/pa26/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/sharp/pa26/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/sharp/pa26/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/sharp/pa26/proprietary/vendor/lib/rfsa/adsp/libapps_mem_heap.so:system/vendor/lib/rfsa/adsp/libapps_mem_heap.so \
    vendor/sharp/pa26/proprietary/vendor/lib/rfsa/adsp/libdspCV_skel.so:system/vendor/lib/rfsa/adsp/libdspCV_skel.so \
    vendor/sharp/pa26/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp.so:system/vendor/lib/rfsa/adsp/libfastcvadsp.so \
    vendor/sharp/pa26/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:system/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so \
    vendor/sharp/pa26/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/sharp/pa26/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/sharp/pa26/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

PRODUCT_PACKAGES += \
    libwpa_qmi_eap_proxy \
    TimeService \
    shutdownlistener \
    qcrilmsgtunnel
